server:
  port: 80
  servlet:
    session:
      cookie:
        name: SESSIONID # 세션 쿠키 이름 설정
        http-only: true # 자바스크립트에서 쿠키 접근 금지
        path: / # 세션 쿠키의 경로 설정
spring:
  thymeleaf:
    prefix : /views/
    suffix : .html
    cache: false
    
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/banzzac_db
    username : banzzac
    password : banzzac00
  
  devtools :
    livereload :
      enalbed : true 

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      
  jwt:
    secret: banzzac01

      
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
kakaopay : 
  admin-key : 45f5d9e931d03368700d096309d522d7
  
kakao:
 api_key : e09ad0168c41380f4ce7f8565f79f0cd
 redirect_uri : http://localhost/api/login/oauth2/code/kakao
#
#custom:
#  path:
#    upload-images : '경로설정'

      