server:
  port: 80

spring:
  thymeleaf:
    prefix : /views/
    suffix : .html
    cache: false
    
    
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/banzzac_db
    username : banzzac
    password : banzzac00
    